spring:
  application:
    name: DeviceManager

  datasource:
    url: jdbc:postgresql://localhost:5432/device_manager
    username: postgres
    password: postgres

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
