INSERT INTO devices (name, brand, state, created_at) VALUES
    ('iPhone 15 Pro',         'Apple',     'AVAILABLE', NOW()),
    ('iPhone 14',             'Apple',     'IN_USE',    NOW()),
    ('Galaxy S24 Ultra',      'Samsung',   'AVAILABLE', NOW()),
    ('Galaxy A54',            'Samsung',   'INACTIVE',  NOW()),
    ('Galaxy Z Fold 5',       'Samsung',   'IN_USE',    NOW()),
    ('Pixel 8 Pro',           'Google',    'AVAILABLE', NOW()),
    ('Pixel 7a',              'Google',    'IN_USE',    NOW()),
    ('OnePlus 12',            'OnePlus',   'AVAILABLE', NOW()),
    ('OnePlus Nord 3',        'OnePlus',   'INACTIVE',  NOW()),
    ('Xperia 1 V',            'Sony',      'AVAILABLE', NOW()),
    ('Xperia 5 V',            'Sony',      'IN_USE',    NOW()),
    ('Edge 40 Pro',           'Motorola',  'AVAILABLE', NOW()),
    ('Edge 30 Fusion',        'Motorola',  'INACTIVE',  NOW()),
    ('P60 Pro',               'Huawei',    'AVAILABLE', NOW()),
    ('Nova 11',               'Huawei',    'IN_USE',    NOW()),
    ('Find X6 Pro',           'OPPO',      'AVAILABLE', NOW()),
    ('ROG Phone 7',           'ASUS',      'INACTIVE',  NOW()),
    ('Mi 13 Pro',             'Xiaomi',    'AVAILABLE', NOW()),
    ('Redmi Note 12 Pro',     'Xiaomi',    'IN_USE',    NOW()),
    ('Nothing Phone 2',       'Nothing',   'AVAILABLE', NOW()),
    ('iPhone 13 Mini',        'Apple',     'INACTIVE',  NOW()),
    ('Galaxy S23 FE',         'Samsung',   'AVAILABLE', NOW()),
    ('Pixel 6a',              'Google',    'INACTIVE',  NOW()),
    ('Xperia 10 V',           'Sony',      'AVAILABLE', NOW()),
    ('OnePlus 11',            'OnePlus',   'IN_USE',    NOW()),
    ('Find X5 Pro',           'OPPO',      'AVAILABLE', NOW()),
    ('Moto G84',              'Motorola',  'IN_USE',    NOW()),
    ('Mi 12T Pro',            'Xiaomi',    'INACTIVE',  NOW()),
    ('Galaxy Z Flip 5',       'Samsung',   'AVAILABLE', NOW()),
    ('Pixel 8',               'Google',    'IN_USE',    NOW());
