INSERT INTO devices (name, brand, state, created_at) VALUES
    ('iPhone 15 Pro',           'Apple',     'AVAILABLE', NOW()),
    ('iPhone 15',               'Apple',     'IN_USE',    NOW()),
    ('iPhone 14 Pro',           'Apple',     'AVAILABLE', NOW()),
    ('iPhone 14',               'Apple',     'IN_USE',    NOW()),
    ('iPhone 13 Mini',          'Apple',     'INACTIVE',  NOW()),
    ('iPhone 13',               'Apple',     'AVAILABLE', NOW()),
    ('iPhone SE 3rd Gen',       'Apple',     'INACTIVE',  NOW()),
    ('Galaxy S24 Ultra',        'Samsung',   'AVAILABLE', NOW()),
    ('Galaxy S24+',             'Samsung',   'IN_USE',    NOW()),
    ('Galaxy S24',              'Samsung',   'AVAILABLE', NOW()),
    ('Galaxy S23 FE',           'Samsung',   'AVAILABLE', NOW()),
    ('Galaxy A54',              'Samsung',   'INACTIVE',  NOW()),
    ('Galaxy A34',              'Samsung',   'IN_USE',    NOW()),
    ('Galaxy Z Fold 5',         'Samsung',   'IN_USE',    NOW()),
    ('Galaxy Z Fold 4',         'Samsung',   'INACTIVE',  NOW()),
    ('Galaxy Z Flip 5',         'Samsung',   'AVAILABLE', NOW()),
    ('Galaxy Z Flip 4',         'Samsung',   'IN_USE',    NOW()),
    ('Pixel 8 Pro',             'Google',    'AVAILABLE', NOW()),
    ('Pixel 8',                 'Google',    'IN_USE',    NOW()),
    ('Pixel 7a',                'Google',    'IN_USE',    NOW()),
    ('Pixel 7',                 'Google',    'AVAILABLE', NOW()),
    ('Pixel 6a',                'Google',    'INACTIVE',  NOW()),
    ('Pixel 6',                 'Google',    'INACTIVE',  NOW()),
    ('Pixel Fold',              'Google',    'AVAILABLE', NOW()),
    ('OnePlus 12',              'OnePlus',   'AVAILABLE', NOW()),
    ('OnePlus 11',              'OnePlus',   'IN_USE',    NOW()),
    ('OnePlus Nord 3',          'OnePlus',   'INACTIVE',  NOW()),
    ('OnePlus Nord CE 3',       'OnePlus',   'AVAILABLE', NOW()),
    ('OnePlus Open',            'OnePlus',   'IN_USE',    NOW()),
    ('Xperia 1 V',              'Sony',      'AVAILABLE', NOW()),
    ('Xperia 5 V',              'Sony',      'IN_USE',    NOW()),
    ('Xperia 10 V',             'Sony',      'AVAILABLE', NOW()),
    ('Xperia 1 IV',             'Sony',      'INACTIVE',  NOW()),
    ('Xperia 5 IV',             'Sony',      'IN_USE',    NOW()),
    ('Edge 40 Pro',             'Motorola',  'AVAILABLE', NOW()),
    ('Edge 40',                 'Motorola',  'IN_USE',    NOW()),
    ('Edge 30 Fusion',          'Motorola',  'INACTIVE',  NOW()),
    ('Moto G84',                'Motorola',  'IN_USE',    NOW()),
    ('Moto G54',                'Motorola',  'AVAILABLE', NOW()),
    ('Razr 40 Ultra',           'Motorola',  'INACTIVE',  NOW()),
    ('P60 Pro',                 'Huawei',    'AVAILABLE', NOW()),
    ('P60',                     'Huawei',    'IN_USE',    NOW()),
    ('Nova 11 Pro',             'Huawei',    'AVAILABLE', NOW()),
    ('Nova 11',                 'Huawei',    'IN_USE',    NOW()),
    ('Mate 60 Pro',             'Huawei',    'INACTIVE',  NOW()),
    ('Find X6 Pro',             'OPPO',      'AVAILABLE', NOW()),
    ('Find X5 Pro',             'OPPO',      'AVAILABLE', NOW()),
    ('Find X5',                 'OPPO',      'INACTIVE',  NOW()),
    ('Reno 10 Pro',             'OPPO',      'IN_USE',    NOW()),
    ('Reno 10',                 'OPPO',      'AVAILABLE', NOW()),
    ('ROG Phone 7 Ultimate',    'ASUS',      'INACTIVE',  NOW()),
    ('ROG Phone 7',             'ASUS',      'AVAILABLE', NOW()),
    ('ROG Phone 6 Pro',         'ASUS',      'IN_USE',    NOW()),
    ('Zenfone 10',              'ASUS',      'AVAILABLE', NOW()),
    ('Zenfone 9',               'ASUS',      'INACTIVE',  NOW()),
    ('Mi 13 Pro',               'Xiaomi',    'AVAILABLE', NOW()),
    ('Mi 13',                   'Xiaomi',    'IN_USE',    NOW()),
    ('Mi 12T Pro',              'Xiaomi',    'INACTIVE',  NOW()),
    ('Redmi Note 13 Pro',       'Xiaomi',    'AVAILABLE', NOW()),
    ('Redmi Note 12 Pro',       'Xiaomi',    'IN_USE',    NOW()),
    ('Redmi Note 12',           'Xiaomi',    'AVAILABLE', NOW()),
    ('POCO F5 Pro',             'Xiaomi',    'INACTIVE',  NOW()),
    ('POCO X5 Pro',             'Xiaomi',    'AVAILABLE', NOW()),
    ('Nothing Phone 2',         'Nothing',   'AVAILABLE', NOW()),
    ('Nothing Phone 1',         'Nothing',   'IN_USE',    NOW()),
    ('Nothing Phone 2a',        'Nothing',   'INACTIVE',  NOW()),
    ('V60 ThinQ',               'LG',        'INACTIVE',  NOW()),
    ('Wing',                    'LG',        'INACTIVE',  NOW()),
    ('Velvet',                  'LG',        'INACTIVE',  NOW()),
    ('Nord N30',                'OnePlus',   'AVAILABLE', NOW()),
    ('A73 5G',                  'OPPO',      'IN_USE',    NOW()),
    ('Reno 8 Pro',              'OPPO',      'INACTIVE',  NOW()),
    ('Redmi 12',                'Xiaomi',    'AVAILABLE', NOW()),
    ('Redmi 12C',               'Xiaomi',    'IN_USE',    NOW()),
    ('MateBook X Pro',          'Huawei',    'AVAILABLE', NOW()),
    ('Galaxy Tab S9 Ultra',     'Samsung',   'IN_USE',    NOW()),
    ('Galaxy Tab S9',           'Samsung',   'AVAILABLE', NOW()),
    ('Galaxy Tab A9+',          'Samsung',   'INACTIVE',  NOW()),
    ('iPad Pro M2',             'Apple',     'AVAILABLE', NOW()),
    ('iPad Air M1',             'Apple',     'IN_USE',    NOW()),
    ('iPad Mini 6',             'Apple',     'INACTIVE',  NOW()),
    ('Pixel Tablet',            'Google',    'AVAILABLE', NOW()),
    ('ROG Phone 6',             'ASUS',      'INACTIVE',  NOW()),
    ('Zenfone 8',               'ASUS',      'IN_USE',    NOW()),
    ('Xperia Pro-I',            'Sony',      'AVAILABLE', NOW()),
    ('Xperia 10 IV',            'Sony',      'INACTIVE',  NOW()),
    ('Edge 20 Pro',             'Motorola',  'IN_USE',    NOW()),
    ('Moto G73',                'Motorola',  'AVAILABLE', NOW()),
    ('Galaxy M54',              'Samsung',   'IN_USE',    NOW()),
    ('Galaxy F54',              'Samsung',   'AVAILABLE', NOW()),
    ('iPhone 12 Pro',           'Apple',     'INACTIVE',  NOW()),
    ('iPhone 12',               'Apple',     'IN_USE',    NOW()),
    ('Pixel 5',                 'Google',    'INACTIVE',  NOW()),
    ('P50 Pro',                 'Huawei',    'INACTIVE',  NOW()),
    ('Find N2 Flip',            'OPPO',      'AVAILABLE', NOW()),
    ('OnePlus 10 Pro',          'OnePlus',   'INACTIVE',  NOW()),
    ('Mi 11 Ultra',             'Xiaomi',    'INACTIVE',  NOW()),
    ('Nothing Phone 2a Plus',   'Nothing',   'AVAILABLE', NOW()),
    ('Redmi Note 11 Pro',       'Xiaomi',    'IN_USE',    NOW()),
    ('POCO M5',                 'Xiaomi',    'AVAILABLE', NOW()),
    ('Galaxy XCover 6 Pro',     'Samsung',   'INACTIVE',  NOW()),
    ('Xperia L4',               'Sony',      'INACTIVE',  NOW()),
    ('Edge Plus 2023',          'Motorola',  'IN_USE',    NOW()),
    ('Reno 6 Pro',              'OPPO',      'INACTIVE',  NOW()),
    ('Find X3 Pro',             'OPPO',      'AVAILABLE', NOW()),
    ('OnePlus 9 Pro',           'OnePlus',   'IN_USE',    NOW()),
    ('Mi 10T Pro',              'Xiaomi',    'INACTIVE',  NOW()),
    ('Galaxy A14',              'Samsung',   'AVAILABLE', NOW()),
    ('Galaxy A24',              'Samsung',   'IN_USE',    NOW()),
    ('iPhone 11 Pro',           'Apple',     'INACTIVE',  NOW()),
    ('iPhone 11',               'Apple',     'INACTIVE',  NOW()),
    ('Pixel 4a',                'Google',    'INACTIVE',  NOW()),
    ('Zenfone 7 Pro',           'ASUS',      'INACTIVE',  NOW()),
    ('ROG Phone 5',             'ASUS',      'AVAILABLE', NOW()),
    ('Xperia 1 III',            'Sony',      'IN_USE',    NOW()),
    ('Find X4 Pro',             'OPPO',      'AVAILABLE', NOW()),
    ('OnePlus Nord 2T',         'OnePlus',   'INACTIVE',  NOW()),
    ('Redmi Note 10 Pro',       'Xiaomi',    'INACTIVE',  NOW()),
    ('Nothing Phone 1a',        'Nothing',   'IN_USE',    NOW()),
    ('Galaxy S22 Ultra',        'Samsung',   'IN_USE',    NOW()),
    ('Galaxy S22',              'Samsung',   'AVAILABLE', NOW()),
    ('Pixel 7 Pro',             'Google',    'IN_USE',    NOW()),
    ('Mi 12 Pro',               'Xiaomi',    'AVAILABLE', NOW()),
    ('Xperia 5 III',            'Sony',      'INACTIVE',  NOW()),
    ('Edge 30 Pro',             'Motorola',  'IN_USE',    NOW()),
    ('Nova 10 Pro',             'Huawei',    'AVAILABLE', NOW()),
    ('P50',                     'Huawei',    'IN_USE',    NOW()),
    ('Reno 8',                  'OPPO',      'AVAILABLE', NOW()),
    ('POCO F4 GT',              'Xiaomi',    'IN_USE',    NOW()),
    ('Razr 2022',               'Motorola',  'INACTIVE',  NOW()),
    ('Galaxy A53',              'Samsung',   'AVAILABLE', NOW()),
    ('Pixel 6 Pro',             'Google',    'IN_USE',    NOW()),
    ('iPhone 15 Plus',          'Apple',     'AVAILABLE', NOW()),
    ('iPhone 14 Plus',          'Apple',     'IN_USE',    NOW()),
    ('Xperia 1 II',             'Sony',      'INACTIVE',  NOW()),
    ('Find X6',                 'OPPO',      'IN_USE',    NOW()),
    ('Galaxy A73',              'Samsung',   'AVAILABLE', NOW()),
    ('OnePlus 10T',             'OnePlus',   'INACTIVE',  NOW()),
    ('Redmi K60 Pro',           'Xiaomi',    'AVAILABLE', NOW()),
    ('Nothing CMF Phone 1',     'Nothing',   'IN_USE',    NOW()),
    ('Moto G Stylus 2023',      'Motorola',  'AVAILABLE', NOW()),
    ('Nova 12 Pro',             'Huawei',    'IN_USE',    NOW()),
    ('ROG Phone 8 Pro',         'ASUS',      'AVAILABLE', NOW()),
    ('Zenfone 11 Ultra',        'ASUS',      'IN_USE',    NOW()),
    ('Galaxy S21 FE',           'Samsung',   'INACTIVE',  NOW()),
    ('iPhone 16 Pro',           'Apple',     'AVAILABLE', NOW()),
    ('iPhone 16',               'Apple',     'IN_USE',    NOW()),
    ('Pixel 9 Pro',             'Google',    'AVAILABLE', NOW()),
    ('Pixel 9',                 'Google',    'IN_USE',    NOW()),
    ('OnePlus 13',              'OnePlus',   'AVAILABLE', NOW());
